// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  var app, bodyParser, express, fs, http, io, multer;

  express = require('express');

  app = express();

  http = require('http').Server(app);

  io = require('socket.io')(http);

  bodyParser = require('body-parser');

  multer = require('multer');

  fs = require("fs");

  app.use(express["static"](__dirname + "/public"));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  app.use(multer());

  app.post("/upload/:file/:token", function(req, res) {
    return res.end("" + req.params.file + " | " + req.params.token);
  });

  app.get("/download/:song", function(req, res) {
    var track, tracklist, _i, _len;
    tracklist = JSON.parse(fs.readFileSync("./public/tracklist.json"));
    for (_i = 0, _len = tracklist.length; _i < _len; _i++) {
      track = tracklist[_i];
      res.write(track.title + "\n");
    }
    return res.end();
  });

  http.listen(3000, function() {
    console.log('listening on *:3000');
  });

  io.on('connection', function(socket) {
    console.log('a user connected');
  });

}).call(this);
